import { useState, useCallback } from "react";
import { toast } from "sonner";
import type { AppraisalResult } from "@/lib/types";
import { formatINR } from "@/lib/currency";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ChevronLeft, Copy, Check, ArrowLeft } from "lucide-react";

interface ListingScreenProps {
  result: AppraisalResult;
  onBack: () => void;
  onReset: () => void;
}

type Platform = "olx" | "facebook" | "quikr" | "ebay";

const PLATFORMS: { id: Platform; label: string }[] = [
  { id: "olx", label: "OLX" },
  { id: "facebook", label: "Facebook" },
  { id: "quikr", label: "Quikr" },
  { id: "ebay", label: "eBay" },
];

export default function ListingScreen({
  result,
  onBack,
  onReset,
}: ListingScreenProps) {
  const [platform, setPlatform] = useState<Platform>(
    (result.bestChannel as Platform) || "olx",
  );
  const [title, setTitle] = useState(result.listingTitle);
  const [description, setDescription] = useState(result.listingDescription);
  const [price, setPrice] = useState(result.askingPrice.toString());
  const [copyState, setCopyState] = useState<"idle" | "copied">("idle");
  const [visibleCounter, setVisibleCounter] = useState(0);

  const handleCopy = useCallback(async () => {
    const formatted = [
      title,
      "",
      description,
      "",
      `💰 Asking: ₹${Number(price).toLocaleString("en-IN")} (negotiable)`,
      "",
      `📱 Listed on ${PLATFORMS.find((p) => p.id === platform)?.label ?? platform}`,
      "",
      "— Generated by Kitna?",
    ].join("\n");

    try {
      await navigator.clipboard.writeText(formatted);
      setCopyState("copied");
      toast.success("Listing copied!", {
        description: "Paste it directly into your marketplace.",
      });
      setTimeout(() => setCopyState("idle"), 2500);
    } catch {
      toast.error("Couldn't copy automatically", {
        description: "Try selecting the text manually.",
      });
    }
  }, [title, description, price, platform]);

  const revealNextCounter = useCallback(() => {
    if (visibleCounter < result.counterLines.length) {
      setVisibleCounter((n) => n + 1);
    }
  }, [visibleCounter, result.counterLines.length]);

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-lg mx-auto px-4 py-6 sm:py-10 space-y-6">
        {/* Back to results */}
        <button
          onClick={onBack}
          className="inline-flex items-center gap-2 text-sm font-medium text-foreground/60 hover:text-foreground transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to appraisal
        </button>

        {/* Header */}
        <header className="space-y-1">
          <p className="text-sm font-medium text-primary uppercase tracking-wider">
            Create your listing
          </p>
          <h1 className="text-2xl font-heading font-semibold text-foreground">
            {result.itemName}
          </h1>
          <p className="text-sm text-foreground/45">{result.brand}</p>
        </header>

        {/* Platform selector */}
        <div className="flex gap-2 flex-wrap">
          {PLATFORMS.map((p) => (
            <button
              key={p.id}
              onClick={() => setPlatform(p.id)}
              className={`px-3.5 py-2 text-xs font-semibold rounded-lg border transition-all duration-200 cursor-pointer ${
                platform === p.id
                  ? "bg-primary text-on-primary border-primary shadow-sm"
                  : "bg-white text-foreground/60 border-border hover:border-primary/30 hover:text-foreground"
              }`}
            >
              {p.label}
            </button>
          ))}
        </div>

        {/* Editable title */}
        <Card className="shadow-card">
          <CardContent className="p-5 space-y-4">
            <div className="space-y-1.5">
              <label
                htmlFor="listing-title"
                className="text-xs font-medium text-foreground/50"
              >
                Title
              </label>
              <input
                id="listing-title"
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg border border-border bg-white text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent transition-shadow"
              />
            </div>

            <div className="space-y-1.5">
              <label
                htmlFor="listing-description"
                className="text-xs font-medium text-foreground/50"
              >
                Description
              </label>
              <textarea
                id="listing-description"
                rows={8}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg border border-border bg-white text-sm text-foreground resize-y focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent transition-shadow"
              />
            </div>

            <div className="space-y-1.5">
              <label
                htmlFor="listing-price"
                className="text-xs font-medium text-foreground/50"
              >
                Asking price (₹)
              </label>
              <input
                id="listing-price"
                type="number"
                value={price}
                onChange={(e) => setPrice(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg border border-border bg-white text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent transition-shadow"
              />
            </div>
          </CardContent>
        </Card>

        {/* Mol-bhaav negotiation card */}
        <Card className="shadow-card border-amber-200/60">
          <CardContent className="p-5 space-y-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-amber-700 uppercase tracking-wider">
                Mol-bhaav — negotiation starters
              </p>
              <Badge variant="outline" className="text-amber-600 border-amber-200">
                {result.counterLines.length - visibleCounter} left
              </Badge>
            </div>
            <p className="text-xs text-foreground/45 leading-relaxed">
              When a buyer tries to negotiate, tap to reveal a response for each round.
            </p>

            <div className="space-y-2">
              {result.counterLines.slice(0, visibleCounter).map((line, i) => (
                <div
                  key={i}
                  className="rounded-lg bg-amber-50 border border-amber-100 px-4 py-3 text-sm text-amber-900 animate-in fade-in slide-in-from-bottom-2 duration-300"
                >
                  <span className="font-medium">Round {i + 1}:</span> {line}
                </div>
              ))}
            </div>

            {visibleCounter < result.counterLines.length && (
              <Button
                variant="outline"
                size="sm"
                onClick={revealNextCounter}
                className="w-full"
              >
                Show next response
              </Button>
            )}

            {visibleCounter >= result.counterLines.length && (
              <p className="text-center text-xs text-amber-600 font-medium">
                You're all set — handle negotiations with confidence! 🎯
              </p>
            )}

            <div className="border-t border-border pt-3 mt-2">
              <div className="flex items-center justify-between text-sm">
                <span className="text-foreground/60">Your floor price</span>
                <span className="font-semibold text-foreground">
                  {formatINR(result.walkAwayFloor)}
                </span>
              </div>
              <p className="text-xs text-foreground/40 mt-1">
                Don't accept below this amount.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Copy button */}
        <Button
          size="lg"
          onClick={handleCopy}
          className="w-full"
          disabled={copyState === "copied"}
        >
          {copyState === "copied" ? (
            <>
              <Check className="w-4 h-4" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="w-4 h-4" />
              Copy listing
            </>
          )}
        </Button>

        {/* Appraise another */}
        <div className="text-center pt-2 pb-8">
          <button
            onClick={onReset}
            className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:text-primary/70 transition-colors cursor-pointer"
          >
            <ChevronLeft className="w-4 h-4" />
            Appraise another item
          </button>
        </div>
      </div>
    </div>
  );
}