import { useState, useCallback, useRef } from "react";
import { toast } from "sonner";
import type { AppraisalResult, ConditionGrade } from "@/lib/types";
import { CONDITION_COLORS } from "@/lib/types";
import { formatINR } from "@/lib/currency";
import {
  generateListingTitle,
  generateListingDescription,
} from "@/lib/demo-data";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import {
  RefreshCw,
  Copy,
  Check,
  Info,
  ExternalLink,
} from "lucide-react";

interface ResultsScreenProps {
  result: AppraisalResult;
  onReset: () => void;
}

type Platform = "olx" | "facebook" | "quikr" | "ebay";
type PriceTab = "new" | "used";

const PLATFORMS: { id: Platform; label: string }[] = [
  { id: "olx", label: "OLX" },
  { id: "facebook", label: "Facebook" },
  { id: "quikr", label: "Quikr" },
  { id: "ebay", label: "eBay" },
];

export default function ResultsScreen({ result, onReset }: ResultsScreenProps) {
  const [priceTab, setPriceTab] = useState<PriceTab>("new");
  const [platform, setPlatform] = useState<Platform>("olx");
  const [title, setTitle] = useState(() =>
    generateListingTitle(result.itemName, result.brand, "olx"),
  );
  const [description, setDescription] = useState(() =>
    generateListingDescription(result, "olx"),
  );
  const [copyState, setCopyState] = useState<"idle" | "copied">("idle");
  const [showTooltip, setShowTooltip] = useState(false);
  const titleInputRef = useRef<HTMLInputElement>(null);
  const descTextareaRef = useRef<HTMLTextAreaElement>(null);

  const handlePlatformChange = useCallback(
    (p: Platform) => {
      setPlatform(p);
      setTitle(generateListingTitle(result.itemName, result.brand, p));
      setDescription(generateListingDescription(result, p));
    },
    [result],
  );

  const handleCopy = useCallback(async () => {
    const formatted = [
      title,
      "",
      description,
      "",
      `💰 Suggested price: ${formatINR(result.resaleRangeLow)} – ${formatINR(result.resaleRangeHigh)} (negotiable)`,
      "",
      `📱 Listed on ${PLATFORMS.find((p) => p.id === platform)?.label ?? platform}`,
      "",
      "— Generated by Kitna?",
    ].join("\n");

    try {
      await navigator.clipboard.writeText(formatted);
      setCopyState("copied");
      toast.success("Listing copied!", {
        description: "Paste it directly into your marketplace.",
      });
      setTimeout(() => setCopyState("idle"), 2500);
    } catch {
      toast.error("Couldn't copy automatically", {
        description: "Try selecting the text manually.",
      });
    }
  }, [title, description, platform, result]);

  const retailLabel = result.priceSource === "estimate" ? "Estimated new" : "New retail";
  const widthPct =
    result.retailPrice && result.retailPrice > 0
      ? Math.min(100, (result.resaleRangeHigh / result.retailPrice) * 100)
      : 0;

  const comparableItems =
    priceTab === "new"
      ? result.comparablePrices
      : [
          { merchant: "OLX Used", price: result.resaleRangeLow, url: "#" },
          { merchant: "OLX Used", price: result.resaleRangeHigh, url: "#" },
        ];

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-lg mx-auto px-4 py-6 sm:py-10 space-y-6">
        {/* Header */}
        <header className="text-center space-y-1">
          <p className="text-sm font-medium text-primary uppercase tracking-wider">
            Appraisal complete
          </p>
          <h1 className="text-2xl font-heading font-semibold text-foreground">
            {result.itemName}
          </h1>
          {result.brand && (
            <p className="text-sm text-foreground/45">{result.brand}</p>
          )}
        </header>

        {/* Price API fallback alert */}
        {result.priceSource === "estimate" && (
          <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            <span className="font-medium">ℹ️</span> Live prices unavailable — showing
            category estimate.
          </div>
        )}

        {/* Hero block: image + resale range */}
        <Card className="overflow-hidden shadow-card">
          <AspectRatio ratio={16 / 9}>
            <img
              src={result.image}
              alt={result.itemName}
              className="w-full h-full object-cover"
            />
          </AspectRatio>
          <CardContent className="pt-5 space-y-3">
            <div className="flex items-center justify-between">
              <div className="space-y-0.5">
                <p className="text-xs font-medium text-foreground/40 uppercase tracking-wider">
                  Your resale value
                </p>
                <div className="flex items-baseline gap-1.5">
                  <span className="text-4xl font-heading font-bold text-primary tracking-tight">
                    {formatINR(result.resaleRangeLow)}
                  </span>
                  <span className="text-foreground/35 text-lg font-medium">–</span>
                  <span className="text-3xl font-heading font-bold text-foreground tracking-tight">
                    {formatINR(result.resaleRangeHigh)}
                  </span>
                </div>
              </div>
              {/* Info tooltip */}
              <div className="relative">
                <button
                  onClick={() => setShowTooltip((v) => !v)}
                  onMouseEnter={() => setShowTooltip(true)}
                  onMouseLeave={() => setShowTooltip(false)}
                  aria-label="How this estimate is calculated"
                  className="w-8 h-8 rounded-full bg-muted flex items-center justify-center hover:bg-border transition-colors cursor-pointer"
                >
                  <Info className="w-4 h-4 text-foreground/50" />
                </button>
                {showTooltip && (
                  <div className="absolute right-0 top-10 z-10 w-64 rounded-xl bg-foreground text-white text-xs p-4 shadow-xl animate-in fade-in slide-in-from-top-2 duration-200">
                    <p className="font-medium mb-1">How this is estimated</p>
                    <p className="opacity-80 leading-relaxed">
                      We combine the item's retail price, condition grade, recent
                      comparable listings, and typical depreciation curves for this
                      category. The range shows what similar items sell for in the
                      current secondhand market.
                    </p>
                    <div className="absolute -top-2 right-3 w-3 h-3 bg-foreground rotate-45" />
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Price gap visual */}
        {result.retailPrice && (
          <Card className="shadow-card">
            <CardContent className="p-5 space-y-3">
              <p className="text-xs font-medium text-foreground/40 uppercase tracking-wider">
                Price comparison
              </p>
              <div className="space-y-2">
                {/* New retail bar */}
                <div className="flex items-center gap-3">
                  <span className="w-20 text-xs text-foreground/50 shrink-0">
                    {retailLabel}
                  </span>
                  <div className="flex-1 h-4 rounded-full bg-muted overflow-hidden">
                    <div
                      className="h-full rounded-full bg-foreground/20 transition-all duration-700 ease-out"
                      style={{ width: "100%" }}
                    />
                  </div>
                  <span className="text-sm font-semibold text-foreground/60 w-24 text-right">
                    {formatINR(result.retailPrice)}
                  </span>
                </div>
                {/* Resale bar */}
                <div className="flex items-center gap-3">
                  <span className="w-20 text-xs text-foreground/50 shrink-0">
                    Your resale
                  </span>
                  <div className="flex-1 h-6 rounded-full bg-primary/10 overflow-hidden">
                    <div
                      className="h-full rounded-full bg-primary transition-all duration-700 ease-out flex items-center justify-end px-2"
                      style={{ width: `${Math.max(widthPct, 15)}%` }}
                    >
                      <span className="text-[10px] font-bold text-white leading-none">
                        {Math.round(widthPct)}%
                      </span>
                    </div>
                  </div>
                  <span className="text-sm font-semibold text-primary w-24 text-right">
                    {formatINR(result.resaleRangeLow)}–{formatINR(result.resaleRangeHigh)}
                  </span>
                </div>
              </div>
              <p className="text-xs text-foreground/35 text-center">
                You could save{" "}
                <span className="font-semibold text-primary">
                  {result.retailPrice
                    ? formatINR(result.retailPrice - result.resaleRangeHigh)
                    : "a lot"}
                </span>{" "}
                vs. buying new
              </p>
            </CardContent>
          </Card>
        )}

        {/* Condition read */}
        <Card className="shadow-card">
          <CardContent className="p-5 space-y-3">
            <p className="text-xs font-medium text-foreground/40 uppercase tracking-wider">
              Condition
            </p>
            <div className="flex items-center gap-2">
              <Badge
                variant="primary"
                className={CONDITION_COLORS[result.conditionGrade as ConditionGrade]}
              >
                {result.conditionGrade}
              </Badge>
            </div>
            <p className="text-sm text-foreground/70 leading-relaxed">
              {result.conditionNotes}
            </p>
            {result.keyAttributes.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {result.keyAttributes.map((attr) => (
                  <Badge key={attr} variant="outline" className="text-xs">
                    {attr}
                  </Badge>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Comparable prices */}
        <Card className="shadow-card">
          <CardContent className="p-5 space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-foreground/40 uppercase tracking-wider">
                Comparable prices
              </p>
              {/* Tabs */}
              <div className="flex gap-1 rounded-lg bg-muted p-0.5">
                <button
                  onClick={() => setPriceTab("new")}
                  className={`px-3 py-1.5 text-xs font-medium rounded-md transition-all duration-200 cursor-pointer ${
                    priceTab === "new"
                      ? "bg-white text-foreground shadow-sm"
                      : "text-foreground/50 hover:text-foreground"
                  }`}
                >
                  Buy new
                </button>
                <button
                  onClick={() => setPriceTab("used")}
                  className={`px-3 py-1.5 text-xs font-medium rounded-md transition-all duration-200 cursor-pointer ${
                    priceTab === "used"
                      ? "bg-white text-foreground shadow-sm"
                      : "text-foreground/50 hover:text-foreground"
                  }`}
                >
                  Used nearby
                </button>
              </div>
            </div>

            <div className="space-y-2">
              {comparableItems.map((item, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between py-2.5 border-b border-border last:border-0"
                >
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-foreground/70">
                      {item.merchant}
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-semibold text-foreground">
                      {formatINR(item.price)}
                    </span>
                    {item.url && priceTab === "new" && (
                      <a
                        href={item.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary hover:text-primary/70 transition-colors"
                      >
                        <ExternalLink className="w-3.5 h-3.5" />
                      </a>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Ready-to-post listing */}
        <Card className="shadow-card border-primary/20">
          <CardContent className="p-5 space-y-4">
            <p className="text-xs font-medium text-primary uppercase tracking-wider">
              Ready-to-post listing
            </p>

            {/* Platform selector */}
            <div className="flex gap-2 flex-wrap">
              {PLATFORMS.map((p) => (
                <button
                  key={p.id}
                  onClick={() => handlePlatformChange(p.id)}
                  className={`px-3.5 py-2 text-xs font-semibold rounded-lg border transition-all duration-200 cursor-pointer ${
                    platform === p.id
                      ? "bg-primary text-on-primary border-primary shadow-sm"
                      : "bg-white text-foreground/60 border-border hover:border-primary/30 hover:text-foreground"
                  }`}
                >
                  {p.label}
                </button>
              ))}
            </div>

            {/* Title input */}
            <div className="space-y-1.5">
              <label
                htmlFor="listing-title"
                className="text-xs font-medium text-foreground/50"
              >
                Title
              </label>
              <input
                ref={titleInputRef}
                id="listing-title"
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg border border-border bg-white text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent transition-shadow"
              />
            </div>

            {/* Description textarea */}
            <div className="space-y-1.5">
              <label
                htmlFor="listing-description"
                className="text-xs font-medium text-foreground/50"
              >
                Description
              </label>
              <textarea
                ref={descTextareaRef}
                id="listing-description"
                rows={8}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                className="w-full px-3.5 py-2.5 rounded-lg border border-border bg-white text-sm text-foreground resize-y focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent transition-shadow"
              />
            </div>

            {/* Suggested price */}
            <div className="space-y-1.5">
              <label
                htmlFor="listing-price"
                className="text-xs font-medium text-foreground/50"
              >
                Suggested price
              </label>
              <input
                id="listing-price"
                type="text"
                readOnly
                value={`${formatINR(result.resaleRangeLow)} – ${formatINR(result.resaleRangeHigh)} (negotiable)`}
                className="w-full px-3.5 py-2.5 rounded-lg bg-muted border border-border text-sm text-foreground/70 cursor-default"
              />
            </div>

            {/* Copy button */}
            <Button
              size="lg"
              onClick={handleCopy}
              className="w-full"
              disabled={copyState === "copied"}
            >
              {copyState === "copied" ? (
                <>
                  <Check className="w-4 h-4" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy listing
                </>
              )}
            </Button>
          </CardContent>
        </Card>

        {/* Appraise another */}
        <div className="text-center pt-2 pb-8">
          <button
            onClick={onReset}
            className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:text-primary/70 transition-colors cursor-pointer"
          >
            <RefreshCw className="w-4 h-4" />
            Appraise another item
          </button>
        </div>
      </div>
    </div>
  );
}