import { useState, useCallback } from "react";
import { toast } from "sonner";
import type { AppraisalResult, ConditionGrade } from "@/lib/types";
import { CONDITION_COLORS } from "@/lib/types";
import { formatINR } from "@/lib/currency";
import { transcribeOnce } from "@/lib/speechmatics";
import { feedbackForAttempt } from "@/lib/molbhaav";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import {
  RefreshCw,
  Info,
  ExternalLink,
  Sparkles,
  Target,
  ArrowRight,
  Camera,
  Handshake,
  Mic,
  Loader2,
} from "lucide-react";

interface ResultsScreenProps {
  result: AppraisalResult;
  onReset: () => void;
  onCreateListing: () => void;
}

const CHANNEL_LABELS: Record<string, string> = {
  olx: "OLX",
  facebook: "Facebook Marketplace",
  quikr: "Quikr",
  ebay: "eBay",
};

/* Confidence band — derived strictly from live comparable count.
   Demo results always read "Estimate only", whatever the sample data holds. */
type ConfidenceBand = "high" | "medium" | "estimate";

function bandForCompCount(count: number): ConfidenceBand {
  return count >= 3 ? "high" : count >= 1 ? "medium" : "estimate";
}

const CONFIDENCE_META: Record<ConfidenceBand, { label: string; className: string }> = {
  high: {
    label: "High confidence",
    className: "bg-emerald-100 text-emerald-700 border-emerald-200",
  },
  medium: {
    label: "Medium confidence",
    className: "bg-amber-100 text-amber-700 border-amber-200",
  },
  estimate: {
    label: "Estimate only",
    className: "bg-orange-100 text-orange-700 border-orange-200",
  },
};

export default function ResultsScreen({
  result,
  onReset,
  onCreateListing,
}: ResultsScreenProps) {
  const [showTooltip, setShowTooltip] = useState(false);
  const [recording, setRecording] = useState(false);
  const [feedback, setFeedback] = useState<string | null>(null);

  const retailLabel = result.priceSource === "estimate" ? "Estimated new" : "New retail";
  const widthPct =
    result.retailPrice && result.retailPrice > 0
      ? Math.min(100, (result.resaleRangeHigh / result.retailPrice) * 100)
      : 0;

  const band: ConfidenceBand = result.isDemo
    ? "estimate"
    : bandForCompCount(result.comparablePrices.length);
  const confidenceMeta = CONFIDENCE_META[band];

  const showLiveComps = !result.isDemo && result.comparablePrices.length > 0;

  const handleCopySummary = useCallback(async () => {
    const summary = [
      `${result.itemName} — ${result.brand}`,
      "",
      `Typical resale: ${formatINR(result.typicalPrice)}`,
      `Resale range: ${formatINR(result.resaleRangeLow)} to ${formatINR(result.resaleRangeHigh)}`,
      `Condition: ${result.conditionGrade}`,
      result.retailPrice
        ? `New retail: ${formatINR(result.retailPrice)}`
        : "New retail: unavailable",
      "",
      "— Generated by Kitna?",
    ].join("\n");
    try {
      await navigator.clipboard.writeText(summary);
      toast.success("Summary copied!");
    } catch {
      toast.error("Couldn't copy automatically", {
        description: "Try selecting the text manually.",
      });
    }
  }, [result]);

  const handlePractice = useCallback(async () => {
    if (recording) return;
    setRecording(true);
    setFeedback(null);
    try {
      const { transcript } = await transcribeOnce(10);
      setFeedback(feedbackForAttempt(result, transcript));
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Couldn't start voice practice", {
        description: "Check that your mic is allowed for this site.",
      });
    } finally {
      setRecording(false);
    }
  }, [recording, result]);

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-lg mx-auto px-4 py-6 sm:py-10 space-y-6">
        {/* Header */}
        <header className="text-center space-y-1">
          <p className="text-sm font-medium text-primary uppercase tracking-wider">
            Appraisal complete
          </p>
          <h1 className="text-2xl font-heading font-semibold text-foreground">
            {result.itemName}
          </h1>
          {result.brand && (
            <p className="text-sm text-foreground/45">{result.brand}</p>
          )}
        </header>

        {/* Hero block: image + resale range + confidence chip */}
        <Card className="overflow-hidden shadow-card">
          <AspectRatio ratio={16 / 9}>
            <img
              src={result.image}
              alt={result.itemName}
              className="w-full h-full object-cover"
            />
          </AspectRatio>
          <CardContent className="pt-5 space-y-3">
            <div className="flex items-center justify-between gap-2">
              <p className="text-xs font-medium text-foreground/40 uppercase tracking-wider">
                Your resale value
              </p>
              <Badge variant="outline" className={`text-[10px] ${confidenceMeta.className}`}>
                {confidenceMeta.label}
              </Badge>
            </div>
            <div className="flex items-start justify-between gap-3">
              <div className="space-y-0.5">
                <div className="flex items-baseline gap-1.5">
                  <span className="text-4xl font-heading font-bold text-primary tracking-tight">
                    {formatINR(result.resaleRangeLow)}
                  </span>
                  <span className="text-foreground/35 text-lg font-medium">to</span>
                  <span className="text-3xl font-heading font-bold text-foreground tracking-tight">
                    {formatINR(result.resaleRangeHigh)}
                  </span>
                </div>
                <p className="text-xs text-foreground/45">
                  Typical:{" "}
                  <span className="font-semibold text-foreground">
                    {formatINR(result.typicalPrice)}
                  </span>
                </p>
              </div>
              {/* Info tooltip */}
              <div className="relative">
                <button
                  onClick={() => setShowTooltip((v) => !v)}
                  onMouseEnter={() => setShowTooltip(true)}
                  onMouseLeave={() => setShowTooltip(false)}
                  aria-label="How this estimate is calculated"
                  className="w-8 h-8 rounded-full bg-muted flex items-center justify-center hover:bg-border transition-colors cursor-pointer active:scale-[0.97]"
                >
                  <Info className="w-4 h-4 text-foreground/50" aria-hidden="true" />
                </button>
                {showTooltip && (
                  <div className="absolute right-0 top-10 z-10 w-64 rounded-xl bg-foreground text-white text-xs p-4 shadow-xl animate-in fade-in slide-in-from-top-2 duration-200">
                    <p className="font-medium mb-1">How this is estimated</p>
                    <p className="opacity-80 leading-relaxed">
                      We combine the item's retail price, condition grade, recent
                      comparable listings, and typical depreciation curves for this
                      category. The range shows what similar items sell for in the
                      current secondhand market.
                    </p>
                    <div className="absolute -top-2 right-3 w-3 h-3 bg-foreground rotate-45" />
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* What I saw in your photo — evidence pinned to the image */}
        <Card className="shadow-card">
          <CardContent className="p-5 space-y-3">
            <div className="flex items-center gap-2">
              <Camera className="w-4 h-4 text-primary" aria-hidden="true" />
              <p className="text-xs font-medium text-primary uppercase tracking-wider">
                What I saw in your photo
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Badge
                variant="primary"
                className={CONDITION_COLORS[result.conditionGrade as ConditionGrade]}
              >
                {result.conditionGrade}
              </Badge>
            </div>
            <p className="text-sm text-foreground/70 leading-relaxed">
              {result.conditionNotes}
            </p>
            {result.keyAttributes.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {result.keyAttributes.map((attr) => (
                  <Badge key={attr} variant="outline" className="text-xs">
                    {attr}
                  </Badge>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Best move card */}
        <Card className="shadow-card border-primary/20">
          <CardContent className="p-5 space-y-3">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-primary" aria-hidden="true" />
              <p className="text-xs font-medium text-primary uppercase tracking-wider">
                Best move
              </p>
            </div>
            <p className="text-sm text-foreground/70 leading-relaxed">
              List on{" "}
              <span className="font-semibold text-foreground">
                {CHANNEL_LABELS[result.bestChannel] ?? result.bestChannel}
              </span>{" "}
              at{" "}
              <span className="font-semibold text-foreground">
                {formatINR(result.suggestedPrice)}
              </span>
              . Don't go below{" "}
              <span className="font-semibold text-foreground">
                {formatINR(result.walkAwayFloor)}
              </span>
              .
            </p>
            <div className="flex items-center gap-2 pt-1">
              <Target className="w-4 h-4 text-foreground/30" aria-hidden="true" />
              <p className="text-xs text-foreground/50">
                Ask {formatINR(result.suggestedPrice)} &middot; floor{" "}
                {formatINR(result.walkAwayFloor)}
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Mol-bhaav — haggle like a local */}
        <Card className="shadow-card border-amber-200/60">
          <CardContent className="p-5 space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-amber-700 uppercase tracking-wider">
                Mol-bhaav — haggle like a local
              </p>
              <Handshake className="w-4 h-4 text-amber-600" aria-hidden="true" />
            </div>

            <div className="flex items-center gap-2 text-sm">
              <span className="text-foreground/60">
                Ask{" "}
                <span className="font-semibold text-foreground">
                  {formatINR(result.askingPrice)}
                </span>
              </span>
              <span className="text-foreground/25">&middot;</span>
              <span className="text-foreground/60">
                Floor{" "}
                <span className="font-semibold text-foreground">
                  {formatINR(result.walkAwayFloor)}
                </span>
              </span>
            </div>

            {result.counterLines[0] && (
              <blockquote className="rounded-lg bg-amber-50 border border-amber-100 px-4 py-3 text-sm text-amber-900">
                “{result.counterLines[0]}”
              </blockquote>
            )}

            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                className="flex-1"
                onClick={onCreateListing}
              >
                See full script
                <ArrowRight className="w-4 h-4" aria-hidden="true" />
              </Button>
              <button
                type="button"
                onClick={handlePractice}
                disabled={recording}
                aria-label={
                  recording
                    ? "Recording — wait for feedback"
                    : "Practice your counter out loud"
                }
                className={`inline-flex items-center justify-center gap-2 rounded-lg px-3.5 py-2 text-xs font-semibold transition-all duration-200 cursor-pointer active:scale-[0.97] disabled:cursor-not-allowed disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 ${
                  recording
                    ? "bg-red-100 text-red-700 border border-red-200 animate-pulse motion-reduce:animate-none"
                    : "bg-amber-500 text-white hover:bg-amber-600 shadow-sm"
                }`}
              >
                {recording ? (
                  <Loader2
                    className="w-4 h-4 animate-spin motion-reduce:animate-none"
                    aria-hidden="true"
                  />
                ) : (
                  <Mic className="w-4 h-4" aria-hidden="true" />
                )}
                {recording ? "Listening…" : "Practice"}
              </button>
            </div>

            {feedback && (
              <p
                role="status"
                className="rounded-lg bg-amber-50 border border-amber-100 px-4 py-3 text-sm text-amber-900 animate-in fade-in slide-in-from-bottom-2 duration-300"
              >
                {feedback}
              </p>
            )}
          </CardContent>
        </Card>

        {/* Price gap visual */}
        {result.retailPrice && (
          <Card className="shadow-card">
            <CardContent className="p-5 space-y-3">
              <p className="text-xs font-medium text-foreground/40 uppercase tracking-wider">
                Price comparison
              </p>
              <div className="space-y-2">
                {/* New retail bar */}
                <div className="flex items-center gap-3">
                  <span className="w-20 text-xs text-foreground/50 shrink-0">
                    {retailLabel}
                  </span>
                  <div className="flex-1 h-4 rounded-full bg-muted overflow-hidden">
                    <div
                      className="h-full rounded-full bg-foreground/20 transition-all duration-700 ease-out"
                      style={{ width: "100%" }}
                    />
                  </div>
                  <span className="text-sm font-semibold text-foreground/60 w-24 text-right">
                    {formatINR(result.retailPrice)}
                  </span>
                </div>
                {/* Resale bar */}
                <div className="flex items-center gap-3">
                  <span className="w-20 text-xs text-foreground/50 shrink-0">
                    Your resale
                  </span>
                  <div className="flex-1 h-6 rounded-full bg-primary/10 overflow-hidden">
                    <div
                      className="h-full rounded-full bg-primary transition-all duration-700 ease-out flex items-center justify-end px-2"
                      style={{ width: `${Math.max(widthPct, 15)}%` }}
                    >
                      <span className="text-[10px] font-bold text-white leading-none">
                        {Math.round(widthPct)}%
                      </span>
                    </div>
                  </div>
                  <span className="text-sm font-semibold text-primary w-24 text-right">
                    {formatINR(result.resaleRangeLow)}–{formatINR(result.resaleRangeHigh)}
                  </span>
                </div>
              </div>
              <p className="text-xs text-foreground/35 text-center">
                You could save{" "}
                <span className="font-semibold text-primary">
                  {result.retailPrice
                    ? formatINR(result.retailPrice - result.resaleRangeHigh)
                    : "a lot"}
                </span>{" "}
                vs. buying new
              </p>
            </CardContent>
          </Card>
        )}

        {/* Comparable prices — real listings only */}
        <Card className="shadow-card">
          <CardContent className="p-5 space-y-3">
            <p className="text-xs font-medium text-foreground/40 uppercase tracking-wider">
              Comparable prices
            </p>

            {showLiveComps ? (
              <>
                <p className="text-sm text-foreground/70">
                  Based on{" "}
                  <span className="font-semibold text-foreground">
                    {result.comparablePrices.length}
                  </span>{" "}
                  live listing{result.comparablePrices.length === 1 ? "" : "s"}
                </p>
                <div className="flex gap-2 overflow-x-auto pb-1 snap-x">
                  {result.comparablePrices.map((comp, i) => (
                    <a
                      key={i}
                      href={comp.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="group shrink-0 snap-start w-40 rounded-xl border border-border bg-muted/50 p-3 hover:border-primary/40 hover:shadow-card transition-all duration-200 cursor-pointer"
                    >
                      <span className="block text-[10px] font-semibold uppercase tracking-wider text-foreground/40 mb-1 truncate">
                        {comp.merchant}
                      </span>
                      <span className="block text-base font-bold text-foreground">
                        {formatINR(comp.price)}
                      </span>
                      <span className="inline-flex items-center gap-1 text-[10px] font-medium text-primary mt-1.5">
                        View listing
                        <ExternalLink className="w-3 h-3" aria-hidden="true" />
                      </span>
                    </a>
                  ))}
                </div>
              </>
            ) : (
              <p className="text-sm text-foreground/45">
                Live comps unavailable, showing a model estimate.
              </p>
            )}
          </CardContent>
        </Card>

        {/* Create listing CTA */}
        <Button size="lg" onClick={onCreateListing} className="w-full">
          Create my listing
          <ArrowRight className="w-4 h-4" aria-hidden="true" />
        </Button>

        {/* Copy summary */}
        <div className="text-center">
          <button
            onClick={handleCopySummary}
            className="text-xs font-medium text-foreground/40 hover:text-foreground/70 transition-colors cursor-pointer"
          >
            Copy summary
          </button>
        </div>

        {/* Appraise another */}
        <div className="text-center pt-2 pb-8">
          <button
            onClick={onReset}
            className="inline-flex items-center gap-2 text-sm font-medium text-primary hover:text-primary/70 transition-colors cursor-pointer"
          >
            <RefreshCw className="w-4 h-4" aria-hidden="true" />
            Appraise another item
          </button>
        </div>
      </div>
    </div>
  );
}
